[package]
name = "sheller"
description = "ğŸš Sheller is a shell command builder library written in Rust."
version = "0.0.2"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["oneofthezombies"]
repository = "https://github.com/oneofthezombies/sheller"
keywords = ["shell", "command"]
